// SQL keywords for syntax highlighting and autocompletion
const SQL_KEYWORDS = [
  "SELECT",
  "FROM",
  "WHERE",
  "GROUP BY",
  "ORDER BY",
  "HAVING",
  "LIMIT",
  "OFFSET",
  "JOIN",
  "LEFT JOIN",
  "RIGHT JOIN",
  "INNER JOIN",
  "OUTER JOIN",
  "ON",
  "AND",
  "OR",
  "NOT",
  "IN",
  "LIKE",
  "ILIKE",
  "IS NULL",
  "IS NOT NULL",
  "AS",
  "UNION",
  "ALL",
  "DISTINCT",
  "COUNT",
  "SUM",
  "AVG",
  "MIN",
  "MAX",
  "CAST",
  "CASE",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "BETWEEN",
  "EXISTS",
  "INSERT",
  "INTO",
  "VALUES",
  "UPDATE",
  "SET",
  "DELETE",
  "CREATE",
  "TABLE",
  "VIEW",
  "DROP",
  "ALTER",
  "ADD",
  "COLUMN",
  "INDEX",
  "PRIMARY KEY",
  "FOREIGN KEY",
  "REFERENCES",
  "DEFAULT",
  "NULL",
  "NOT NULL",
  "WITH",
  "RECURSIVE",
  "USING",
];

// DuckDB specific functions
const DUCKDB_FUNCTIONS = [
  "DATE_PART",
  "EXTRACT",
  "CURRENT_DATE",
  "CURRENT_TIME",
  "CURRENT_TIMESTAMP",
  "STRFTIME",
  "CONCAT",
  "STRING_AGG",
  "SUBSTRING",
  "REGEXP_MATCHES",
  "COALESCE",
  "NULLIF",
  "IFF",
  "IF",
  "TYPEOF",
  "LIST",
  "STRUCT",
  "MAP",
  "MAP_EXTRACT",
  "LIST_EXTRACT",
  "STRUCT_EXTRACT",
  "TO_TIMESTAMP",
  "TO_DATE",
  "ROUND",
  "FLOOR",
  "CEIL",
  "GREATEST",
  "LEAST",
  "ABS",
  "REPLACE",
  "TRANSLATE",
  "TRIM",
  "LTRIM",
  "RTRIM",
  "LOWER",
  "UPPER",
];

// Common SQL snippets
const SQL_SNIPPETS = [
  {
    label: "sel",
    detail: "SELECT ... FROM ... WHERE ...",
    insertText: "SELECT $1\nFROM $2\nWHERE $3;",
    insertTextRules: 4, // Explicitly use snippets
    kind: 15, // Snippet
  },
  {
    label: "selall",
    detail: "SELECT * FROM ...",
    insertText: "SELECT *\nFROM $1\nWHERE $2;",
    insertTextRules: 4,
    kind: 15,
  },
  {
    label: "join",
    detail: "SELECT ... FROM ... JOIN ... ON ...",
    insertText: "SELECT $1\nFROM $2\nJOIN $3 ON $4;",
    insertTextRules: 4,
    kind: 15,
  },
  {
    label: "groupby",
    detail: "SELECT ... FROM ... GROUP BY ...",
    insertText: "SELECT $1\nFROM $2\nGROUP BY $3;",
    insertTextRules: 4,
    kind: 15,
  },
  {
    label: "createview",
    detail: "CREATE VIEW ... AS SELECT ...",
    insertText: "CREATE VIEW $1 AS\nSELECT $2\nFROM $3;",
    insertTextRules: 4,
    kind: 15,
  },
];

export { DUCKDB_FUNCTIONS, SQL_KEYWORDS, SQL_SNIPPETS };
